### ISSUE TITLE
Working with a database works, the problem is ResponseEntity not return as expected ps worked.

### ISSUE THREAD

**Issue by Mladen94** [milos01/NetAdvert#13]

**Comment by Mladen94** [comment]
ResponseEntity negde radi kako treba negde baca gresku "Cannot call sendError()" Npr za dodavanje komentara vracao je lepo json sve do sada, a sada ne vrati response a pri tom u bazi sve lepo uradi. Ukoliko neko zna resenje za problem neka sredi.

**Comment by Milosh94** [comment]
Problem solved using appropriate json annotations and custom serializers
